spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/mini-mall?useUnicode=true&characterEncoding=utf-8&useSSL=false


file:
  basePath: E:/data/mall/static
  tempPath: /temp
  adPath: /ad
  domain: http://www.mini-mall.com



